### ISSUE TITLE
Add update_jrc_author function to doi_common

### ISSUE THREAD

**Issue by robsv** [JaneliaSciComp/doi_common#2]

**Comment by robsv** [comment]
Fuction should generate jrc_author list. This list will be written to the dois collection, and also returned to the calling program

**Comment by virginiascarlett** [comment]
Stray authors identified through fuzzy name matching can be added to ORCID collection first, and then I can update the DOI collection with this function OR with a POST request to jrc_authors

**Comment by virginiascarlett** [comment]
Update: Perhaps this function is not necessary. I can just update the ORCID records and then run update_dois.py.

**Comment by virginiascarlett** [comment]
name_match.py now gives the user the option to run update_dois.py at the end. New records in the orcid collection are then automatically added to jrc_authors IF an exact name match exists. 

In theory, we should get a name match every time, because I've added a bunch of permutations of the author name to the orcid record. But I still want to test this with some tricky names.

**Comment by virginiascarlett** [comment]
Update: Rob already created this function, so I will refactor my script to use that function instead of calling update_dois.py.

**Comment by virginiascarlett** [comment]
Implemented. doi_common.update_jrc_authors() works well.

**Comment by virginiascarlett** [comment]
With a caveat--see #57

**Comment by virginiascarlett** [comment]
I don't have permissions to close this issue but I am satisfied with it, ok to close
